// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRf1L1vtZ4JKacIG5-eG5S7VtZCnRnrcg',
    appId: '1:353564014906:web:663f2be089bc0380ddb803',
    messagingSenderId: '353564014906',
    projectId: 'e-project-1af4d',
    authDomain: 'e-project-1af4d.firebaseapp.com',
    storageBucket: 'e-project-1af4d.appspot.com',
    measurementId: 'G-947LV3WDR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhge6TX7dOsv10OLG16mtVQjkS6ObCZyE',
    appId: '1:353564014906:android:cdbecd9e0e09a52fddb803',
    messagingSenderId: '353564014906',
    projectId: 'e-project-1af4d',
    storageBucket: 'e-project-1af4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGR6c8rsbgm0gE7CwHjQvqkvEiVgtaDlI',
    appId: '1:353564014906:ios:15fafa0fa8f78b99ddb803',
    messagingSenderId: '353564014906',
    projectId: 'e-project-1af4d',
    storageBucket: 'e-project-1af4d.appspot.com',
    iosBundleId: 'com.example.eProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGR6c8rsbgm0gE7CwHjQvqkvEiVgtaDlI',
    appId: '1:353564014906:ios:e910e0534885ffebddb803',
    messagingSenderId: '353564014906',
    projectId: 'e-project-1af4d',
    storageBucket: 'e-project-1af4d.appspot.com',
    iosBundleId: 'com.example.eProject.RunnerTests',
  );
}
